### ISSUE TITLE
distribute replicas to different zones and racks

### ISSUE THREAD

**Issue by huachaohuang** [pingcap/pd#454]
We want to distribute replicas to different zones and racks.
We can add configurations to let PD understand the cluster topology like this:
```
[replication]
distribution-labels = ["zone", "rack"]
max-peer-count = 3
```
The priorities of zone and rack are implied by the order specified in `distribution-labels`.
Then PD can schedule replicas to different zones, then to different racks if we don't have enough zones.

In the future, we need to support distribute some replicas to the same zones or racks like this:
```
[constraints]
labels = ["zone=us-west"]
replicas = 2
```
Then we will schedule 2 replicas to different racks in zone "us-west", and schedule other replicas to different racks in different zones.

Note that we also need to keep balance between different zones and racks, which can be complicated.

**Comment by huachaohuang** [comment]
PTAL @ngaut @siddontang @shenli

**Comment by shenli** [comment]
How about use max-replicas/min-replicas instead of replicas?

**Comment by huachaohuang** [comment]
I found a reference from [elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/allocation-awareness.html).

**Comment by huachaohuang** [comment]
For now, we only need to place replicas to different zones/racks/hosts. We only need to add a general configuration to tell PD about the topology of the stores like this:
```toml
[replication]
# We need 3 replicas for each region.
replicas = 3
# Placement priorities to tolerate failure: "zone" > "rack" > "host".
location-labels = ["zone", "rack", "host"]
```
Then PD will place replicas to different zones first, then different racks and different hosts. This should be enough now, we can support more constraints in the future.

**Comment by huachaohuang** [comment]
@shenli suggests a more general solution like:
```toml
[[rule]]
labels = ["zone"]
priority = 100
max-replicas = 1
min-replicas = 0

[[rule]]
labels = ["rack"]
priority = 50
max-replicas = 1
min-replicas = 0

[[rule]]
labels = ["disk=ssd"]
priority = 1
leader = 1
```
It is more flexible, but I think it is hard to implement for now, and I'm not very clear about the relationship between these rules, so I think I should start with my solution above, and we can have further discussion later.
